USE PPIJ;
GO

INSERT INTO element (Name, Info, File_path) VALUES ('H','x','');
INSERT INTO element (Name, Info, File_path) VALUES ('He','x','x','Noble gas');
INSERT INTO element (Name, Info, File_path) VALUES ('Li','x','x','Alkali metal');
INSERT INTO element (Name, Info, File_path) VALUES ('Be','x','x','Alkaline earth metal');
INSERT INTO element (Name, Info, File_path) VALUES ('B','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('C','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('N','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('O','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('F','x','x','Halogen');
INSERT INTO element (Name, Info, File_path) VALUES ('Ne','x','x','Noble gas');
INSERT INTO element (Name, Info, File_path) VALUES ('Na','x','x','Alkali metal');
INSERT INTO element (Name, Info, File_path) VALUES ('Mg','x','x','Alkaline earth metal');
INSERT INTO element (Name, Info, File_path) VALUES ('Al','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('Si','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('P','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('S','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('Cl','x','x','Halogen');
INSERT INTO element (Name, Info, File_path) VALUES ('Ar','x','x','Noble gas');
INSERT INTO element (Name, Info, File_path) VALUES ('K','x','x','Alkali metal');
INSERT INTO element (Name, Info, File_path) VALUES ('Ca','x','x','Alkaline earth metal');
INSERT INTO element (Name, Info, File_path) VALUES ('Sc','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('Ti','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('V','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('Cr','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('Mn','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('Fe','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('Co','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('Ni','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('Cu','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('Zn','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('Ga','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('Ge','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('As','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('Se','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('Br','x','x','Halogen');
INSERT INTO element (Name, Info, File_path) VALUES ('Kr','x','x','Noble gas');
INSERT INTO element (Name, Info, File_path) VALUES ('Rb','x','x','Alkali metal');
INSERT INTO element (Name, Info, File_path) VALUES ('Sr','x','x','Alkaline earth metal');
INSERT INTO element (Name, Info, File_path) VALUES ('Y','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('Zr','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('Nb','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('Mo','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('Tc','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('Ru','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('Rh','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('Pd','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('Ag','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('Cd','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('In','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('Sn','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('Sb','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('Te','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('I','x','x','Halogen');
INSERT INTO element (Name, Info, File_path) VALUES ('Xe','x','x','Noble gas');
INSERT INTO element (Name, Info, File_path) VALUES ('Cs','x','x','Alkali metal');
INSERT INTO element (Name, Info, File_path) VALUES ('Ba','x','x','Alkaline earth metal');
INSERT INTO element (Name, Info, File_path) VALUES ('La','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('Ce','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('Pr','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('Nd','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('Pm','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('Sm','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('Eu','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('Gd','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('Tb','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('Dy','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('Ho','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('Er','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('Tm','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('Yb','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('Lu','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('Hf','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('Ta','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('W','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('Re','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('Os','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('Ir','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('Pt','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('Au','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('Hg','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('Tl','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('Pb','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('Bi','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('Po','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('At','x','x','Halogen');
INSERT INTO element (Name, Info, File_path) VALUES ('Rn','x','x','Noble gas');
INSERT INTO element (Name, Info, File_path) VALUES ('Fr','x','x','Alkali metal');
INSERT INTO element (Name, Info, File_path) VALUES ('Ra','x','x','Alkaline earth metal');
INSERT INTO element (Name, Info, File_path) VALUES ('Ac','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('Th','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('Pa','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('U','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('Np','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('Pu','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('Am','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('Cm','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('Bk','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('Cf','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('Es','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('Fm','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('Md','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('No','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('Lr','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('Rf','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('Db','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('Sg','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('Bh','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('Hs','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('Mt','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('Ds','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('Rg','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('Cn','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('Uut','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('Fl','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('Uup','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('Lv','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('Uus','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('Uuo','x','x');
GO

INSERT INTO quiz (Question, Answer, A1, A2, A3, A4) VALUES ('Who discovered phosphorus ?', 1, 'Hennig Brand','Marie Curie','Antoine Laurent de Lavoisier','Alfred Nobel');
INSERT INTO quiz (Question, Answer, A1, A2, A3, A4) VALUES ('What is the first element in the periodic table?', 2, 'Methane', 'Hydrogen', 'Calcium', 'Potassium');
INSERT INTO quiz (Question, Answer, A1, A2, A3, A4) VALUES ('Oxygen (O) has a greater mass than chlorine (Cl)', 1, 'True', 'False');
INSERT INTO quiz (Question, Answer, A1, A2, A3, A4) VALUES ('About how many known elements are in the periodic table?', 4 , '100', '83', '181', '118');
INSERT INTO quiz (Question, Answer, A1, A2, A3, A4) VALUES ('Halogens are very...', 1, 'Reactive', 'Stable', 'Heavy', 'Radioactive');
INSERT INTO quiz (Question, Answer, A1, A2, A3, A4) VALUES ('Where can you easily find halogens in the natural world?', 3, 'In amalgams with metals ', 'Not bonded to other elements ', 'In salt compounds with metals ', 'None of the above ');
INSERT INTO quiz (Question, Answer, A1, A2, A3, A4) VALUES ('What is the element symbol for Sulfur?', 2,'Su', 'S', 'Sr', 'Si');
INSERT INTO quiz (Question, Answer, A1, A2, A3, A4) VALUES ('What is the atomic number of Phosphorous (P)?', 2, '31 ', '15', '38', '56');
INSERT INTO quiz (Question, Answer, A1, A2, A3, A4) VALUES ('What is the atomic mass of Phosphorous (P)?', 1, '31 ', '15', '38', '56');
INSERT INTO quiz (Question, Answer, A1, A2, A3, A4) VALUES ('What is the name of the element with the symbol Fe?', 3, 'Selenium', 'Fermium', 'Iron', 'Oxygen');
INSERT INTO quiz (Question, Answer, A1, A2, A3, A4) VALUES ('Magnesium (Mg) is a:', 1, 'Metal', 'Non metal', '','');
INSERT INTO quiz (Question, Answer, A1, A2, A3, A4) VALUES ('Chlorine (Cl) is a:', 2,'Metal', 'Non metal', '','');
INSERT INTO quiz (Question, Answer, A1, A2, A3, A4) VALUES ('Manganese (Mn) is a:',1 ,'Metal', 'Non metal', '','');
INSERT INTO quiz (Question, Answer, A1, A2, A3, A4) VALUES ('The elements in the alkali metals are all part of the same:',1 , 'Family', 'Period', 'Element', 'Transition');
INSERT INTO quiz (Question, Answer, A1, A2, A3, A4) VALUES ('Elements in the same family have similar properties?',1, 'True', 'False', '', '');
INSERT INTO quiz (Question, Answer, A1, A2, A3, A4) VALUES ('How many protons does Lithium (Li) have?',2, '4', '3', '10', '6.9');
INSERT INTO quiz (Question, Answer, A1, A2, A3, A4) VALUES ('How many neutrons does Lithium (Li) have?', 1, '4', '3', '6', '1');
INSERT INTO quiz (Question, Answer, A1, A2, A3, A4) VALUES ('How many electrons does Lithium (Li) have?', 2, '4', '3', '10', '5');
INSERT INTO quiz (Question, Answer, A1, A2, A3, A4) VALUES ('Symbol for Cobalt', 2 , 'Cr', 'Co', 'Cu', 'Ca');
INSERT INTO quiz (Question, Answer, A1, A2, A3, A4) VALUES ('Symbol for Flerovium', 3 , 'Fr', 'Fe', 'Fl', 'Rh');
INSERT INTO quiz (Question, Answer, A1, A2, A3, A4) VALUES ('Symbol for Bismuth', 2 , 'B', 'Bi', 'Be', 'Ba');
INSERT INTO quiz (Question, Answer, A1, A2, A3, A4) VALUES ('Symbol for Polonium',4 , 'Pt', 'Pb', 'P', 'Po');
INSERT INTO quiz (Question, Answer, A1, A2, A3, A4) VALUES ('Symbol for Ununseptium', 4, 'Uut', 'Uup', 'Uuo', 'Uus');
INSERT INTO quiz (Question, Answer, A1, A2, A3, A4) VALUES ('Under ordinary, room temperature conditions, the greatest number of elements are',3 , 'gases', 'liquids', ' metallic solids. ', 'nonmetallic plasmas. ');
INSERT INTO quiz (Question, Answer, A1, A2, A3, A4) VALUES (' A solution of sugar dissolved in water is?', 2, 'a heterogeneous mixture. ', ' a homogeneous mixture. ', 'an alloy. ', ' a pure substance. ');
INSERT INTO quiz (Question, Answer, A1, A2, A3, A4) VALUES ('Which of the following represents a physical change?',3 , 'Electricity is used to generate oxygen and hydrogen from water. ', ' Calcium carbonate is dissolved by stomach acid.', '. Solid ice is melted into liquid water. ', ' Natural gas is burned as a heat source. ');
INSERT INTO quiz (Question, Answer, A1, A2, A3, A4) VALUES ('Carbon cannot be broken down into anything simpler by chemical means, so carbon must be', 3 , 'a heterogeneous mixture. ', ' a homogeneous mixture. ', ' an element. ', 'a compound. ');
INSERT INTO quiz (Question, Answer, A1, A2, A3, A4) VALUES ('Compared to metals, nonmetals are', 4, ' better conductors of heat. ', 'more ductile as a solid', 'better electrical conductors. ', 'more brittle as a solid. ');
INSERT INTO quiz (Question, Answer, A1, A2, A3, A4) VALUES ('How many naturally occurring elements are found on the earth in significant quantities?',3 , '112 ', '92 ', '89 ', '32 ');
INSERT INTO quiz (Question, Answer, A1, A2, A3, A4) VALUES ('', , '', '', '', '');

GO

INSERT INTO did_you_know (Fact) VALUES ('Did you know that dynamite contains peanuts as an ingredient !');
INSERT INTO did_you_know (Fact) VALUES ('While Dmitri Mendeleev is most often cited as the inventor of the modern periodic table, his table was just the first to gain scientific credibility, and not the first table that organized the elements according to periodic properties');
INSERT INTO did_you_know (Fact) VALUES ('There are 90 elements on the periodic table that occur in nature. All of the other elements are strictly man-made.');
INSERT INTO did_you_know (Fact) VALUES ('Technetium was the first element to be made artificially.');
INSERT INTO did_you_know (Fact) VALUES ('The present periodic table has room for 118 elements. Elements aren''t discovered or created in order of atomic number. Scientists are working on creating and verifying element 120, which will change the appearance of the table.');
INSERT INTO did_you_know (Fact) VALUES (' Noble gases (far right on the periodic table) have closed shells of electrons, which is why they are nearly inert.');
INSERT INTO did_you_know (Fact) VALUES ('Liquid nitrogen boils at 77 kelvin (−196 °C, −321 °F).');
INSERT INTO did_you_know (Fact) VALUES ('Around 1% of the sun’s mass is oxygen.');
INSERT INTO did_you_know (Fact) VALUES ('Carbon comes in a number of different forms (allotropes), these include diamond, graphite and impure forms such as coal.');
INSERT INTO did_you_know (Fact) VALUES ('Although it is still debated, it is largely recognized that the word ''chemistry'' comes from an Egyptian word meaning ''earth''.');
INSERT INTO did_you_know (Fact) VALUES ('Above 4 °C, water expands when heated and contracts when cooled. But between 4 °C and 0 °C it does the opposite, contracting when heated and expanding when cooled. Stronger hydrogen and oxygen bonds are formed as the water crystallizes into ice. By the time it''s frozen it takes up around 9% more space.');
INSERT INTO did_you_know (Fact) VALUES ('Athletes at the Olympic Games have to be careful how much coffee they drink. The caffeine in coffee is a banned substance because it can enhance performance. One or two cups are fine but they can go over the limit with more than five. (update - as of 2004 caffeine has been taken back off the WADA banned list but its use will be closely monitored to prevent future abuse by athletes.)');
INSERT INTO did_you_know (Fact) VALUES ('Often formed under intense pressure over time, a crystal is made up of molecules or atoms that are repeated in a three dimensional repeating pattern. Quartz is a well known example of a crystal.');
INSERT INTO did_you_know (Fact) VALUES ('Chemical reactions occur all the time, including through everyday activities such as cooking. Try adding an acid such as vinegar to a base such as baking soda and see what happens!');
INSERT INTO did_you_know (Fact) VALUES ('Humans breathe out carbon dioxide (CO2). Using energy from sunlight, plants convert carbon dioxide into food during a process called photosynthesis.');
INSERT INTO did_you_know (Fact) VALUES ('Things invisible to the human eye can often be seen under UV light, which comes in handy for both scientists and detectives.');
INSERT INTO did_you_know (Fact) VALUES ('The use of various forms of chemistry is believed to go back as long ago as the Ancient Egyptians. By 1000 BC civilizations were using more complex forms of chemistry such as using plants for medicine, extracting metal from ores, fermenting wine and making cosmetics.');
INSERT INTO did_you_know (Fact) VALUES ('Although it is still debated, it is largely recognized that the word ''chemistry'' comes from an Egyptian word meaning ''earth''.');
INSERT INTO did_you_know (Fact) VALUES ('Under normal conditions, oil and water do not mix.');
INSERT INTO did_you_know (Fact) VALUES ('Helium is lighter than the air around us so it floats, that''s why it is perfect for the balloons you get at parties.');
INSERT INTO did_you_know (Fact) VALUES ('Hydrogen is the first element on the periodic table. It has an atomic number of 1. It is highly flammable and is the most common element found in our universe.');

GO