INSERT INTO QuizWith4Ans (Question, Answer, A1, A2, A3, A4) VALUES ('Who discovered phosphorus ?', 1, 'Hennig Brand','Marie Curie','Antoine Laurent de Lavoisier','Alfred Nobel');
INSERT INTO QuizWith4Ans (Question, Answer, A1, A2, A3, A4) VALUES ('What is the first element in the periodic table?', 2, 'Methane', 'Hydrogen', 'Calcium', 'Potassium');
INSERT INTO QuizWith4Ans (Question, Answer, A1, A2, A3, A4) VALUES ('About how many known elements are in the periodic table?', 4 , '100', '83', '181', '118');
INSERT INTO QuizWith4Ans (Question, Answer, A1, A2, A3, A4) VALUES ('Halogens are very...', 1, 'Reactive', 'Stable', 'Heavy', 'Radioactive');
INSERT INTO QuizWith4Ans (Question, Answer, A1, A2, A3, A4) VALUES ('Where can you easily find halogens in the natural world?', 3, 'In amalgams with metals ', 'Not bonded to other elements ', 'In salt compounds with metals ', 'None of the above ');
INSERT INTO QuizWith4Ans (Question, Answer, A1, A2, A3, A4) VALUES ('What is the element symbol for Sulfur?', 2,'Su', 'S', 'Sr', 'Si');
INSERT INTO QuizWith4Ans (Question, Answer, A1, A2, A3, A4) VALUES ('What is the atomic number of Phosphorous (P)?', 2, '31 ', '15', '38', '56');
INSERT INTO QuizWith4Ans (Question, Answer, A1, A2, A3, A4) VALUES ('What is the atomic mass of Phosphorous (P)?', 1, '31 ', '15', '38', '56');
INSERT INTO QuizWith4Ans (Question, Answer, A1, A2, A3, A4) VALUES ('What is the name of the element with the symbol Fe?', 3, 'Selenium', 'Fermium', 'Iron', 'Oxygen');
INSERT INTO QuizWith4Ans (Question, Answer, A1, A2, A3, A4) VALUES ('The elements in the alkali metals are all part of the same:',1 , 'Family', 'Period', 'Element', 'Transition');
INSERT INTO QuizWith4Ans (Question, Answer, A1, A2, A3, A4) VALUES ('How many protons does Lithium (Li) have?',2, '4', '3', '10', '6.9');
INSERT INTO QuizWith4Ans (Question, Answer, A1, A2, A3, A4) VALUES ('How many neutrons does Lithium (Li) have?', 1, '4', '3', '6', '1');
INSERT INTO QuizWith4Ans (Question, Answer, A1, A2, A3, A4) VALUES ('How many electrons does Lithium (Li) have?', 2, '4', '3', '10', '5');
INSERT INTO QuizWith4Ans (Question, Answer, A1, A2, A3, A4) VALUES ('Symbol for Cobalt', 2 , 'Cr', 'Co', 'Cu', 'Ca');
INSERT INTO QuizWith4Ans (Question, Answer, A1, A2, A3, A4) VALUES ('Symbol for Flerovium', 3 , 'Fr', 'Fe', 'Fl', 'Rh');
INSERT INTO QuizWith4Ans (Question, Answer, A1, A2, A3, A4) VALUES ('Symbol for Bismuth', 2 , 'B', 'Bi', 'Be', 'Ba');
INSERT INTO QuizWith4Ans (Question, Answer, A1, A2, A3, A4) VALUES ('Symbol for Polonium',4 , 'Pt', 'Pb', 'P', 'Po');
INSERT INTO QuizWith4Ans (Question, Answer, A1, A2, A3, A4) VALUES ('Symbol for Ununseptium', 4, 'Uut', 'Uup', 'Uuo', 'Uus');
INSERT INTO QuizWith4Ans (Question, Answer, A1, A2, A3, A4) VALUES ('Under ordinary, room temperature conditions, the greatest number of elements are',3 , 'gases', 'liquids', ' metallic solids. ', 'nonmetallic plasmas. ');
INSERT INTO QuizWith4Ans (Question, Answer, A1, A2, A3, A4) VALUES ('A solution of sugar dissolved in water is?', 2, 'a heterogeneous mixture. ', ' a homogeneous mixture. ', 'an alloy. ', ' a pure substance. ');
INSERT INTO QuizWith4Ans (Question, Answer, A1, A2, A3, A4) VALUES ('Which of the following represents a physical change?',3 , 'Electricity is used to generate oxygen and hydrogen from water. ', ' Calcium carbonate is dissolved by stomach acid.', '. Solid ice is melted into liquid water. ', ' Natural gas is burned as a heat source. ');
INSERT INTO QuizWith4Ans (Question, Answer, A1, A2, A3, A4) VALUES ('Carbon cannot be broken down into anything simpler by chemical means, so carbon must be', 3 , 'a heterogeneous mixture. ', ' a homogeneous mixture. ', ' an element. ', 'a compound. ');
INSERT INTO QuizWith4Ans (Question, Answer, A1, A2, A3, A4) VALUES ('Compared to metals, nonmetals are', 4, ' better conductors of heat. ', 'more ductile as a solid', 'better electrical conductors. ', 'more brittle as a solid. ');
INSERT INTO QuizWith4Ans (Question, Answer, A1, A2, A3, A4) VALUES ('How many naturally occurring elements are found on the earth in significant quantities?',3 , '112 ', '92 ', '89 ', '32 ');
GO

INSERT INTO QuizYesNo (Question, Answer, A1, A2) VALUES ('Oxygen (O) has a greater mass than chlorine (Cl)', 1, 'True', 'False');
INSERT INTO QuizYesNo (Question, Answer, A1, A2) VALUES ('Magnesium (Mg) is a:', 1, 'Metal', 'Non metal');
INSERT INTO QuizYesNo (Question, Answer, A1, A2) VALUES ('Chlorine (Cl) is a:', 2,'Metal', 'Non metal');
INSERT INTO QuizYesNo (Question, Answer, A1, A2) VALUES ('Manganese (Mn) is a:',1 ,'Metal', 'Non metal');
INSERT INTO QuizYesNo (Question, Answer, A1, A2) VALUES ('Elements in the same family have similar properties?',1, 'True', 'False');
GO

INSERT INTO QuizPictures (ImagePath, Answer, ImageFile) SELECT 'water.jpg', 'voda', * FROM OPENROWSET(BULK 'D:\water.jpg', SINGLE_BLOB) rs;
GO

INSERT INTO DidYouKnow (Fact) VALUES ('Did you know that dynamite contains peanuts as an ingredient !');
INSERT INTO DidYouKnow (Fact) VALUES ('While Dmitri Mendeleev is most often cited as the inventor of the modern periodic table, his table was just the first to gain scientific credibility, and not the first table that organized the elements according to periodic properties');
INSERT INTO DidYouKnow (Fact) VALUES ('There are 90 elements on the periodic table that occur in nature. All of the other elements are strictly man-made.');
INSERT INTO DidYouKnow (Fact) VALUES ('Technetium was the first element to be made artificially.');
INSERT INTO DidYouKnow (Fact) VALUES ('The present periodic table has room for 118 elements. Elements aren''t discovered or created in order of atomic number. Scientists are working on creating and verifying element 120, which will change the appearance of the table.');
INSERT INTO DidYouKnow (Fact) VALUES ('Noble gases (far right on the periodic table) have closed shells of electrons, which is why they are nearly inert.');
INSERT INTO DidYouKnow (Fact) VALUES ('Liquid nitrogen boils at 77 kelvin (−196 °C, −321 °F).');
INSERT INTO DidYouKnow (Fact) VALUES ('Around 1% of the sun’s mass is oxygen.');
INSERT INTO DidYouKnow (Fact) VALUES ('Carbon comes in a number of different forms (allotropes), these include diamond, graphite and impure forms such as coal.');
INSERT INTO DidYouKnow (Fact) VALUES ('Although it is still debated, it is largely recognized that the word ''chemistry'' comes from an Egyptian word meaning ''earth''.');
INSERT INTO DidYouKnow (Fact) VALUES ('Above 4 °C, water expands when heated and contracts when cooled. But between 4 °C and 0 °C it does the opposite, contracting when heated and expanding when cooled. Stronger hydrogen and oxygen bonds are formed as the water crystallizes into ice. By the time it''s frozen it takes up around 9% more space.');
INSERT INTO DidYouKnow (Fact) VALUES ('Athletes at the Olympic Games have to be careful how much coffee they drink. The caffeine in coffee is a banned substance because it can enhance performance. One or two cups are fine but they can go over the limit with more than five. (update - as of 2004 caffeine has been taken back off the WADA banned list but its use will be closely monitored to prevent future abuse by athletes.)');
INSERT INTO DidYouKnow (Fact) VALUES ('Often formed under intense pressure over time, a crystal is made up of molecules or atoms that are repeated in a three dimensional repeating pattern. Quartz is a well known example of a crystal.');
INSERT INTO DidYouKnow (Fact) VALUES ('Chemical reactions occur all the time, including through everyday activities such as cooking. Try adding an acid such as vinegar to a base such as baking soda and see what happens!');
INSERT INTO DidYouKnow (Fact) VALUES ('Humans breathe out carbon dioxide (CO2). Using energy from sunlight, plants convert carbon dioxide into food during a process called photosynthesis.');
INSERT INTO DidYouKnow (Fact) VALUES ('Things invisible to the human eye can often be seen under UV light, which comes in handy for both scientists and detectives.');
INSERT INTO DidYouKnow (Fact) VALUES ('The use of various forms of chemistry is believed to go back as long ago as the Ancient Egyptians. By 1000 BC civilizations were using more complex forms of chemistry such as using plants for medicine, extracting metal from ores, fermenting wine and making cosmetics.');
INSERT INTO DidYouKnow (Fact) VALUES ('Although it is still debated, it is largely recognized that the word ''chemistry'' comes from an Egyptian word meaning ''earth''.');
INSERT INTO DidYouKnow (Fact) VALUES ('Under normal conditions, oil and water do not mix.');
INSERT INTO DidYouKnow (Fact) VALUES ('Helium is lighter than the air around us so it floats, that''s why it is perfect for the balloons you get at parties.');
INSERT INTO DidYouKnow (Fact) VALUES ('Hydrogen is the first element on the periodic table. It has an atomic number of 1. It is highly flammable and is the most common element found in our universe.');
INSERT INTO DidYouKnow (Fact) VALUES ('Liquid oxygen is blue.');
INSERT INTO DidYouKnow (Fact) VALUES ('Some radioactive elements really do glow.');
INSERT INTO DidYouKnow (Fact) VALUES ('You can die from drinking too much water.');
INSERT INTO DidYouKnow (Fact) VALUES ('If you mix half a liter of alcohol with half a liter of water, the volume \nof the mixture will be less than one liter.');
INSERT INTO DidYouKnow (Fact) VALUES ('Liquid water is more dense than solid water (ice).');
INSERT INTO DidYouKnow (Fact) VALUES ('You can melt a sample of the element gallium \njust by holding it in your hand.');
INSERT INTO DidYouKnow (Fact) VALUES ('Under certain conditions, hot water will \nfreeze more quickly than cold water.');
INSERT INTO DidYouKnow (Fact) VALUES ('You cant solidify helium at normal pressures, even \nat absolute zero. (You can solidify \nit at extremely high pressure and low temperature.)');
INSERT INTO DidYouKnow (Fact) VALUES ('You cant taste food without saliva.');
INSERT INTO DidYouKnow (Fact) VALUES ('Fish scales are a common lipstick ingredient.');
INSERT INTO DidYouKnow (Fact) VALUES ('Some lipstick contains lead acetate or sugar \nof lead. This toxic lead compound makes the lipstick taste sweet.');
INSERT INTO DidYouKnow (Fact) VALUES ('The average shot of espresso contains less caffeine than a typical cup of coffee.');
INSERT INTO DidYouKnow (Fact) VALUES ('Coca Cola originally contained cocaine.');
INSERT INTO DidYouKnow (Fact) VALUES ('Lemons contain more sugar than strawberries, for the same mass.');
INSERT INTO DidYouKnow (Fact) VALUES ('Lobster blood is colorless until it is exposed to air. Then the blood appears blue.');
INSERT INTO DidYouKnow (Fact) VALUES ('Goldfish eyes perceive not only the visible spectrum, but also infrared and ultraviolet light.');
INSERT INTO DidYouKnow (Fact) VALUES ('When you freeze saltwater or seawater slowly, you get freshwater ice. Icebergs are freshwater, too, although that is because they come \nfrom glaciers, which are made from freshwater (snow).');
INSERT INTO DidYouKnow (Fact) VALUES ('Urh je jak.');
INSERT INTO DidYouKnow (Fact) VALUES ('If you exposed a glass of water to space, it \nwould boil rather than freeze. However, the water vapor would \ncrystallize into ice afterward.');
INSERT INTO DidYouKnow (Fact) VALUES ('Fresh egg will sink in fresh water. A stale egg will float.');
INSERT INTO DidYouKnow (Fact) VALUES ('The wallpaper in Napoleons room was dyed with Scheeles \nGreen, which contains copper arsenide. In 1893 the \nItalian biochemist Gosio found that \ndampening wallpaper containing Scheeles Green allowed a mold to convert the \ncopper arsenide into poisonous arsenic vapor. Although this may not have been the \ncause of Napoleons death, it certainly cant have helped his health!');
INSERT INTO DidYouKnow (Fact) VALUES ('Sound travels 4.3 times faster in water than in \nair. Of course, it doesnt travel through a vacuum at all.');
INSERT INTO DidYouKnow (Fact) VALUES ('About 78% of the average human brain consists of water.');
INSERT INTO DidYouKnow (Fact) VALUES ('Macadamia nuts are toxic dogs.');
INSERT INTO DidYouKnow (Fact) VALUES ('A lightning strike can reach a temperature of \n30,000 degrees Celsius or 54,000 degrees Fahrenheit.');
INSERT INTO DidYouKnow (Fact) VALUES ('Fire typically spreads uphill more quickly than downhill. \nThis is because temperature affects the rate of combustion. \nThe region above a fire tends to be much hotter than the area below it, plus \nit may have a better supply of fresh air.');
INSERT INTO DidYouKnow (Fact) VALUES ('Frogs dont need to drink water since they \ncan absorb it through their skin. Humans, on the other hand, have waterproofing \nproteins in their skin to help prevent water loss.');
INSERT INTO DidYouKnow (Fact) VALUES ('The hardest chemical in your body is your tooth enamel.');
INSERT INTO DidYouKnow (Fact) VALUES ('Urine fluoresces or glows under ultraviolet light.');
INSERT INTO DidYouKnow (Fact) VALUES ('Pearls, bones and teeth will dissolve in \nvinegar, which contains weak acetic acid.');
INSERT INTO DidYouKnow (Fact) VALUES ('The chemical name for water is dihydrogen monoxide.');
INSERT INTO DidYouKnow (Fact) VALUES ('You can extend the life of rubberbands by \nstoring them in the refrigerator.');
INSERT INTO DidYouKnow (Fact) VALUES ('The ethylene gas produced by a ripening apple \nripens other apples as well as many other types \nof produce.');
INSERT INTO DidYouKnow (Fact) VALUES ('Water expands about 9% when it freezes into ice.');
INSERT INTO DidYouKnow (Fact) VALUES ('Mars is red because its surface contains a lot of iron oxide or rust.');
INSERT INTO DidYouKnow (Fact) VALUES ('Youve lost about 1% of your bodys water by the time you feel thirsty.');
INSERT INTO DidYouKnow (Fact) VALUES ('You have chemoreceptors or taste buds on the inside of your cheek \nas well as on your tongue.');
INSERT INTO DidYouKnow (Fact) VALUES ('The only elements that are liquid at room temperature are \nbromine and mercury. However, you can melt gallium by holding a lump in the \nwarmth of your hand.');
INSERT INTO DidYouKnow (Fact) VALUES ('Unlike many substances, water expands as it freezes. \nAn ice cube takes up about 9% more volume than the \nwater used to make it.');
INSERT INTO DidYouKnow (Fact) VALUES ('If you pour a handful of salt into a full glass of water, the water \nlevel will actually go down rather \nthan overflowing the glass.');
INSERT INTO DidYouKnow (Fact) VALUES ('There is about 1/2 lb or 250 g of salt (NaCl) in the average adult human body.');
INSERT INTO DidYouKnow (Fact) VALUES ('A pure element can take many forms. For example, diamond and \ngraphite both are forms of pure carbon.');
INSERT INTO DidYouKnow (Fact) VALUES ('The chemical name for water (H2O) is dihydrogen monoxide.');
INSERT INTO DidYouKnow (Fact) VALUES ('The only letter that doesnt appear on the periodic table is J.');
INSERT INTO DidYouKnow (Fact) VALUES ('Lightning strikes produce O3, which is ozone, and strengthen \nthe ozone layer of the atmosphere.');
INSERT INTO DidYouKnow (Fact) VALUES ('The only two non-silvery metals are gold and copper.');
INSERT INTO DidYouKnow (Fact) VALUES ('Although oxygen gas is colorless, the liquid and solid forms \nof oxygen are blue.');
INSERT INTO DidYouKnow (Fact) VALUES ('The human body contains enough carbon to provide lead \n(which is really graphite) for about 9,000 pencils.');
INSERT INTO DidYouKnow (Fact) VALUES ('Hydrogen is the most abundant element in the universe, while \noxygen is the most abundant element in the earths \natmosphere, crust, and oceans (about 49.5%).');
INSERT INTO DidYouKnow (Fact) VALUES ('The rarest naturally-occurring element in the \nearths crust may be astatine. The entire crust appears to contain about \n28 g of the element.');
INSERT INTO DidYouKnow (Fact) VALUES ('Hydrofluoric acid is so corrosive that it will dissolve glass. \nAlthough it is corrosive, hydrofluoric acid is considered to be a weak acid.');
INSERT INTO DidYouKnow (Fact) VALUES ('One bucket full of water contains more atoms than \nthere are bucketfuls of water in the Atlantic ocean.');
INSERT INTO DidYouKnow (Fact) VALUES ('Approximately 20% of the oxygen in the atmosphere was \nproduced by the Amazon rainforest.');
INSERT INTO DidYouKnow (Fact) VALUES ('Helium balloons float because helium is lighter than air.');
INSERT INTO DidYouKnow (Fact) VALUES ('Bee stings are acidic while wasp stings are alkaline.');
INSERT INTO DidYouKnow (Fact) VALUES ('Hot peppers get their heat from a molecule \ncalled capsaicin. While the molecule acts as an irritant to mammals, including \nhumans, birds lack the receptor responsible for the effect and are immune to \nthe burning sensation from exposure.');
INSERT INTO DidYouKnow (Fact) VALUES ('Dry ice is the solid form of carbon dioxide, CO2.');
INSERT INTO DidYouKnow (Fact) VALUES ('Liquid air has a bluish tint, similar to water.');
GO