USE PPIJ;
GO

INSERT INTO element (Name, Info, File_path) VALUES ('H','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('He','x','x','Noble gas');
INSERT INTO element (Name, Info, File_path) VALUES ('Li','x','x','Alkali metal');
INSERT INTO element (Name, Info, File_path) VALUES ('Be','x','x','Alkaline earth metal');
INSERT INTO element (Name, Info, File_path) VALUES ('B','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('C','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('N','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('O','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('F','x','x','Halogen');
INSERT INTO element (Name, Info, File_path) VALUES ('Ne','x','x','Noble gas');
INSERT INTO element (Name, Info, File_path) VALUES ('Na','x','x','Alkali metal');
INSERT INTO element (Name, Info, File_path) VALUES ('Mg','x','x','Alkaline earth metal');
INSERT INTO element (Name, Info, File_path) VALUES ('Al','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('Si','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('P','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('S','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('Cl','x','x','Halogen');
INSERT INTO element (Name, Info, File_path) VALUES ('Ar','x','x','Noble gas');
INSERT INTO element (Name, Info, File_path) VALUES ('K','x','x','Alkali metal');
INSERT INTO element (Name, Info, File_path) VALUES ('Ca','x','x','Alkaline earth metal');
INSERT INTO element (Name, Info, File_path) VALUES ('Sc','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('Ti','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('V','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('Cr','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('Mn','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('Fe','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('Co','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('Ni','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('Cu','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('Zn','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('Ga','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('Ge','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('As','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('Se','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('Br','x','x','Halogen');
INSERT INTO element (Name, Info, File_path) VALUES ('Kr','x','x','Noble gas');
INSERT INTO element (Name, Info, File_path) VALUES ('Rb','x','x','Alkali metal');
INSERT INTO element (Name, Info, File_path) VALUES ('Sr','x','x','Alkaline earth metal');
INSERT INTO element (Name, Info, File_path) VALUES ('Y','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('Zr','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('Nb','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('Mo','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('Tc','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('Ru','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('Rh','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('Pd','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('Ag','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('Cd','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('In','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('Sn','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('Sb','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('Te','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('I','x','x','Halogen');
INSERT INTO element (Name, Info, File_path) VALUES ('Xe','x','x','Noble gas');
INSERT INTO element (Name, Info, File_path) VALUES ('Cs','x','x','Alkali metal');
INSERT INTO element (Name, Info, File_path) VALUES ('Ba','x','x','Alkaline earth metal');
INSERT INTO element (Name, Info, File_path) VALUES ('La','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('Ce','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('Pr','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('Nd','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('Pm','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('Sm','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('Eu','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('Gd','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('Tb','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('Dy','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('Ho','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('Er','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('Tm','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('Yb','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('Lu','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('Hf','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('Ta','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('W','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('Re','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('Os','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('Ir','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('Pt','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('Au','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('Hg','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('Tl','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('Pb','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('Bi','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('Po','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('At','x','x','Halogen');
INSERT INTO element (Name, Info, File_path) VALUES ('Rn','x','x','Noble gas');
INSERT INTO element (Name, Info, File_path) VALUES ('Fr','x','x','Alkali metal');
INSERT INTO element (Name, Info, File_path) VALUES ('Ra','x','x','Alkaline earth metal');
INSERT INTO element (Name, Info, File_path) VALUES ('Ac','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('Th','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('Pa','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('U','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('Np','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('Pu','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('Am','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('Cm','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('Bk','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('Cf','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('Es','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('Fm','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('Md','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('No','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('Lr','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('Rf','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('Db','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('Sg','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('Bh','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('Hs','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('Mt','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('Ds','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('Rg','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('Cn','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('Uut','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('Fl','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('Uup','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('Lv','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('Uus','x','x');
INSERT INTO element (Name, Info, File_path) VALUES ('Uuo','x','x');
GO

INSERT INTO quiz (Question, Answer, A1, A2, A3, A4) VALUES ('Who discovered phosphorus ?', 1, 'Hennig Brand','Marie Curie','Antoine Laurent de Lavoisier','Alfred Nobel');
INSERT INTO quiz (Question, Answer, A1, A2, A3, A4) VALUES ('', 1, '', '', '', '');
INSERT INTO quiz (Question, Answer, A1, A2, A3, A4) VALUES ('', 1, '', '', '', '');
INSERT INTO quiz (Question, Answer, A1, A2, A3, A4) VALUES ('', 1, '', '', '', '');
INSERT INTO quiz (Question, Answer, A1, A2, A3, A4) VALUES ('', 1, '', '', '', '');
INSERT INTO quiz (Question, Answer, A1, A2, A3, A4) VALUES ('', 1, '', '', '', '');
INSERT INTO quiz (Question, Answer, A1, A2, A3, A4) VALUES ('', 1, '', '', '', '');
INSERT INTO quiz (Question, Answer, A1, A2, A3, A4) VALUES ('', 1, '', '', '', '');
INSERT INTO quiz (Question, Answer, A1, A2, A3, A4) VALUES ('', 1, '', '', '', '');
INSERT INTO quiz (Question, Answer, A1, A2, A3, A4) VALUES ('', 1, '', '', '', '');
GO

INSERT INTO did_you_know (Fact) VALUES ('Did you know that dynamite contains peanuts as an ingredient !');
INSERT INTO did_you_know (Fact) VALUES ('');
INSERT INTO did_you_know (Fact) VALUES ('');
INSERT INTO did_you_know (Fact) VALUES ('');
INSERT INTO did_you_know (Fact) VALUES ('');
INSERT INTO did_you_know (Fact) VALUES ('');
INSERT INTO did_you_know (Fact) VALUES ('');
INSERT INTO did_you_know (Fact) VALUES ('');
INSERT INTO did_you_know (Fact) VALUES ('');
INSERT INTO did_you_know (Fact) VALUES ('');
INSERT INTO did_you_know (Fact) VALUES ('');
GO